/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiServicesRouteImport } from './routes/api.services'
import { Route as ApiProfessionalsRouteImport } from './routes/api.professionals'
import { Route as ApiProfessionalSpacesRouteImport } from './routes/api.professional-spaces'
import { Route as ApiProfessionalInquiryRouteImport } from './routes/api.professional-inquiry'
import { Route as ApiProductsRouteImport } from './routes/api.products'
import { Route as ApiNewsletterRouteImport } from './routes/api.newsletter'
import { Route as ApiMarketingSlidesRouteImport } from './routes/api.marketing-slides'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ApiCartRequestRouteImport } from './routes/api.cart-request'
import { Route as ApiBookingRouteImport } from './routes/api.booking'
import { Route as AdminServicosRouteImport } from './routes/admin.servicos'
import { Route as AdminProfissionaisRouteImport } from './routes/admin.profissionais'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAgendamentosRouteImport } from './routes/admin.agendamentos'
import { Route as ApiBookingAvailabilityRouteImport } from './routes/api.booking.availability'
import { Route as ApiAdminServicesRouteImport } from './routes/api.admin.services'
import { Route as ApiAdminProfessionalsRouteImport } from './routes/api.admin.professionals'
import { Route as ApiAdminProfessionalSpacesRouteImport } from './routes/api.admin.professional-spaces'
import { Route as ApiAdminProductsRouteImport } from './routes/api.admin.products'
import { Route as ApiAdminMarketingSlidesRouteImport } from './routes/api.admin.marketing-slides'
import { Route as ApiAdminLogoutRouteImport } from './routes/api.admin.logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api.admin.login'
import { Route as ApiAdminDashboardRouteImport } from './routes/api.admin.dashboard'
import { Route as ApiAdminAppointmentsRouteImport } from './routes/api.admin.appointments'
import { Route as ApiAdminServicesServiceIdRouteImport } from './routes/api.admin.services.$serviceId'
import { Route as ApiAdminProfessionalsProfessionalIdRouteImport } from './routes/api.admin.professionals.$professionalId'
import { Route as ApiAdminProfessionalSpacesSpaceIdRouteImport } from './routes/api.admin.professional-spaces.$spaceId'
import { Route as ApiAdminProductsProductIdRouteImport } from './routes/api.admin.products.$productId'
import { Route as ApiAdminMarketingSlidesSlideIdRouteImport } from './routes/api.admin.marketing-slides.$slideId'
import { Route as ApiAdminAppointmentsAppointmentIdRouteImport } from './routes/api.admin.appointments.$appointmentId'
import { Route as ApiAdminAppointmentsAppointmentIdEmailRouteImport } from './routes/api.admin.appointments.$appointmentId.email'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesRoute = ApiServicesRouteImport.update({
  id: '/api/services',
  path: '/api/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfessionalsRoute = ApiProfessionalsRouteImport.update({
  id: '/api/professionals',
  path: '/api/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfessionalSpacesRoute = ApiProfessionalSpacesRouteImport.update({
  id: '/api/professional-spaces',
  path: '/api/professional-spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfessionalInquiryRoute = ApiProfessionalInquiryRouteImport.update({
  id: '/api/professional-inquiry',
  path: '/api/professional-inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterRoute = ApiNewsletterRouteImport.update({
  id: '/api/newsletter',
  path: '/api/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketingSlidesRoute = ApiMarketingSlidesRouteImport.update({
  id: '/api/marketing-slides',
  path: '/api/marketing-slides',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartRequestRoute = ApiCartRequestRouteImport.update({
  id: '/api/cart-request',
  path: '/api/cart-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingRoute = ApiBookingRouteImport.update({
  id: '/api/booking',
  path: '/api/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicosRoute = AdminServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfissionaisRoute = AdminProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendamentosRoute = AdminAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => AdminRoute,
} as any)
const ApiBookingAvailabilityRoute = ApiBookingAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => ApiBookingRoute,
} as any)
const ApiAdminServicesRoute = ApiAdminServicesRouteImport.update({
  id: '/api/admin/services',
  path: '/api/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProfessionalsRoute = ApiAdminProfessionalsRouteImport.update({
  id: '/api/admin/professionals',
  path: '/api/admin/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProfessionalSpacesRoute =
  ApiAdminProfessionalSpacesRouteImport.update({
    id: '/api/admin/professional-spaces',
    path: '/api/admin/professional-spaces',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminProductsRoute = ApiAdminProductsRouteImport.update({
  id: '/api/admin/products',
  path: '/api/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMarketingSlidesRoute = ApiAdminMarketingSlidesRouteImport.update({
  id: '/api/admin/marketing-slides',
  path: '/api/admin/marketing-slides',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAppointmentsRoute = ApiAdminAppointmentsRouteImport.update({
  id: '/api/admin/appointments',
  path: '/api/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminServicesServiceIdRoute =
  ApiAdminServicesServiceIdRouteImport.update({
    id: '/$serviceId',
    path: '/$serviceId',
    getParentRoute: () => ApiAdminServicesRoute,
  } as any)
const ApiAdminProfessionalsProfessionalIdRoute =
  ApiAdminProfessionalsProfessionalIdRouteImport.update({
    id: '/$professionalId',
    path: '/$professionalId',
    getParentRoute: () => ApiAdminProfessionalsRoute,
  } as any)
const ApiAdminProfessionalSpacesSpaceIdRoute =
  ApiAdminProfessionalSpacesSpaceIdRouteImport.update({
    id: '/$spaceId',
    path: '/$spaceId',
    getParentRoute: () => ApiAdminProfessionalSpacesRoute,
  } as any)
const ApiAdminProductsProductIdRoute =
  ApiAdminProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => ApiAdminProductsRoute,
  } as any)
const ApiAdminMarketingSlidesSlideIdRoute =
  ApiAdminMarketingSlidesSlideIdRouteImport.update({
    id: '/$slideId',
    path: '/$slideId',
    getParentRoute: () => ApiAdminMarketingSlidesRoute,
  } as any)
const ApiAdminAppointmentsAppointmentIdRoute =
  ApiAdminAppointmentsAppointmentIdRouteImport.update({
    id: '/$appointmentId',
    path: '/$appointmentId',
    getParentRoute: () => ApiAdminAppointmentsRoute,
  } as any)
const ApiAdminAppointmentsAppointmentIdEmailRoute =
  ApiAdminAppointmentsAppointmentIdEmailRouteImport.update({
    id: '/email',
    path: '/email',
    getParentRoute: () => ApiAdminAppointmentsAppointmentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendamento': typeof AgendamentoRoute
  '/contactos': typeof ContactosRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/loja': typeof LojaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/profissionais': typeof ProfissionaisRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/profissionais': typeof AdminProfissionaisRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/api/booking': typeof ApiBookingRouteWithChildren
  '/api/cart-request': typeof ApiCartRequestRoute
  '/api/contact': typeof ApiContactRoute
  '/api/health': typeof ApiHealthRoute
  '/api/marketing-slides': typeof ApiMarketingSlidesRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/products': typeof ApiProductsRoute
  '/api/professional-inquiry': typeof ApiProfessionalInquiryRoute
  '/api/professional-spaces': typeof ApiProfessionalSpacesRoute
  '/api/professionals': typeof ApiProfessionalsRoute
  '/api/services': typeof ApiServicesRoute
  '/api/admin/appointments': typeof ApiAdminAppointmentsRouteWithChildren
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/marketing-slides': typeof ApiAdminMarketingSlidesRouteWithChildren
  '/api/admin/products': typeof ApiAdminProductsRouteWithChildren
  '/api/admin/professional-spaces': typeof ApiAdminProfessionalSpacesRouteWithChildren
  '/api/admin/professionals': typeof ApiAdminProfessionalsRouteWithChildren
  '/api/admin/services': typeof ApiAdminServicesRouteWithChildren
  '/api/booking/availability': typeof ApiBookingAvailabilityRoute
  '/api/admin/appointments/$appointmentId': typeof ApiAdminAppointmentsAppointmentIdRouteWithChildren
  '/api/admin/marketing-slides/$slideId': typeof ApiAdminMarketingSlidesSlideIdRoute
  '/api/admin/products/$productId': typeof ApiAdminProductsProductIdRoute
  '/api/admin/professional-spaces/$spaceId': typeof ApiAdminProfessionalSpacesSpaceIdRoute
  '/api/admin/professionals/$professionalId': typeof ApiAdminProfessionalsProfessionalIdRoute
  '/api/admin/services/$serviceId': typeof ApiAdminServicesServiceIdRoute
  '/api/admin/appointments/$appointmentId/email': typeof ApiAdminAppointmentsAppointmentIdEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendamento': typeof AgendamentoRoute
  '/contactos': typeof ContactosRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/loja': typeof LojaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/profissionais': typeof ProfissionaisRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/profissionais': typeof AdminProfissionaisRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/api/booking': typeof ApiBookingRouteWithChildren
  '/api/cart-request': typeof ApiCartRequestRoute
  '/api/contact': typeof ApiContactRoute
  '/api/health': typeof ApiHealthRoute
  '/api/marketing-slides': typeof ApiMarketingSlidesRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/products': typeof ApiProductsRoute
  '/api/professional-inquiry': typeof ApiProfessionalInquiryRoute
  '/api/professional-spaces': typeof ApiProfessionalSpacesRoute
  '/api/professionals': typeof ApiProfessionalsRoute
  '/api/services': typeof ApiServicesRoute
  '/api/admin/appointments': typeof ApiAdminAppointmentsRouteWithChildren
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/marketing-slides': typeof ApiAdminMarketingSlidesRouteWithChildren
  '/api/admin/products': typeof ApiAdminProductsRouteWithChildren
  '/api/admin/professional-spaces': typeof ApiAdminProfessionalSpacesRouteWithChildren
  '/api/admin/professionals': typeof ApiAdminProfessionalsRouteWithChildren
  '/api/admin/services': typeof ApiAdminServicesRouteWithChildren
  '/api/booking/availability': typeof ApiBookingAvailabilityRoute
  '/api/admin/appointments/$appointmentId': typeof ApiAdminAppointmentsAppointmentIdRouteWithChildren
  '/api/admin/marketing-slides/$slideId': typeof ApiAdminMarketingSlidesSlideIdRoute
  '/api/admin/products/$productId': typeof ApiAdminProductsProductIdRoute
  '/api/admin/professional-spaces/$spaceId': typeof ApiAdminProfessionalSpacesSpaceIdRoute
  '/api/admin/professionals/$professionalId': typeof ApiAdminProfessionalsProfessionalIdRoute
  '/api/admin/services/$serviceId': typeof ApiAdminServicesServiceIdRoute
  '/api/admin/appointments/$appointmentId/email': typeof ApiAdminAppointmentsAppointmentIdEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendamento': typeof AgendamentoRoute
  '/contactos': typeof ContactosRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/loja': typeof LojaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/profissionais': typeof ProfissionaisRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/profissionais': typeof AdminProfissionaisRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/api/booking': typeof ApiBookingRouteWithChildren
  '/api/cart-request': typeof ApiCartRequestRoute
  '/api/contact': typeof ApiContactRoute
  '/api/health': typeof ApiHealthRoute
  '/api/marketing-slides': typeof ApiMarketingSlidesRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/api/products': typeof ApiProductsRoute
  '/api/professional-inquiry': typeof ApiProfessionalInquiryRoute
  '/api/professional-spaces': typeof ApiProfessionalSpacesRoute
  '/api/professionals': typeof ApiProfessionalsRoute
  '/api/services': typeof ApiServicesRoute
  '/api/admin/appointments': typeof ApiAdminAppointmentsRouteWithChildren
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/marketing-slides': typeof ApiAdminMarketingSlidesRouteWithChildren
  '/api/admin/products': typeof ApiAdminProductsRouteWithChildren
  '/api/admin/professional-spaces': typeof ApiAdminProfessionalSpacesRouteWithChildren
  '/api/admin/professionals': typeof ApiAdminProfessionalsRouteWithChildren
  '/api/admin/services': typeof ApiAdminServicesRouteWithChildren
  '/api/booking/availability': typeof ApiBookingAvailabilityRoute
  '/api/admin/appointments/$appointmentId': typeof ApiAdminAppointmentsAppointmentIdRouteWithChildren
  '/api/admin/marketing-slides/$slideId': typeof ApiAdminMarketingSlidesSlideIdRoute
  '/api/admin/products/$productId': typeof ApiAdminProductsProductIdRoute
  '/api/admin/professional-spaces/$spaceId': typeof ApiAdminProfessionalSpacesSpaceIdRoute
  '/api/admin/professionals/$professionalId': typeof ApiAdminProfessionalsProfessionalIdRoute
  '/api/admin/services/$serviceId': typeof ApiAdminServicesServiceIdRoute
  '/api/admin/appointments/$appointmentId/email': typeof ApiAdminAppointmentsAppointmentIdEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agendamento'
    | '/contactos'
    | '/faq'
    | '/galeria'
    | '/loja'
    | '/privacidade'
    | '/profissionais'
    | '/servicos'
    | '/sobre'
    | '/termos'
    | '/admin/agendamentos'
    | '/admin/login'
    | '/admin/marketing'
    | '/admin/produtos'
    | '/admin/profissionais'
    | '/admin/servicos'
    | '/api/booking'
    | '/api/cart-request'
    | '/api/contact'
    | '/api/health'
    | '/api/marketing-slides'
    | '/api/newsletter'
    | '/api/products'
    | '/api/professional-inquiry'
    | '/api/professional-spaces'
    | '/api/professionals'
    | '/api/services'
    | '/api/admin/appointments'
    | '/api/admin/dashboard'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/marketing-slides'
    | '/api/admin/products'
    | '/api/admin/professional-spaces'
    | '/api/admin/professionals'
    | '/api/admin/services'
    | '/api/booking/availability'
    | '/api/admin/appointments/$appointmentId'
    | '/api/admin/marketing-slides/$slideId'
    | '/api/admin/products/$productId'
    | '/api/admin/professional-spaces/$spaceId'
    | '/api/admin/professionals/$professionalId'
    | '/api/admin/services/$serviceId'
    | '/api/admin/appointments/$appointmentId/email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agendamento'
    | '/contactos'
    | '/faq'
    | '/galeria'
    | '/loja'
    | '/privacidade'
    | '/profissionais'
    | '/servicos'
    | '/sobre'
    | '/termos'
    | '/admin/agendamentos'
    | '/admin/login'
    | '/admin/marketing'
    | '/admin/produtos'
    | '/admin/profissionais'
    | '/admin/servicos'
    | '/api/booking'
    | '/api/cart-request'
    | '/api/contact'
    | '/api/health'
    | '/api/marketing-slides'
    | '/api/newsletter'
    | '/api/products'
    | '/api/professional-inquiry'
    | '/api/professional-spaces'
    | '/api/professionals'
    | '/api/services'
    | '/api/admin/appointments'
    | '/api/admin/dashboard'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/marketing-slides'
    | '/api/admin/products'
    | '/api/admin/professional-spaces'
    | '/api/admin/professionals'
    | '/api/admin/services'
    | '/api/booking/availability'
    | '/api/admin/appointments/$appointmentId'
    | '/api/admin/marketing-slides/$slideId'
    | '/api/admin/products/$productId'
    | '/api/admin/professional-spaces/$spaceId'
    | '/api/admin/professionals/$professionalId'
    | '/api/admin/services/$serviceId'
    | '/api/admin/appointments/$appointmentId/email'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agendamento'
    | '/contactos'
    | '/faq'
    | '/galeria'
    | '/loja'
    | '/privacidade'
    | '/profissionais'
    | '/servicos'
    | '/sobre'
    | '/termos'
    | '/admin/agendamentos'
    | '/admin/login'
    | '/admin/marketing'
    | '/admin/produtos'
    | '/admin/profissionais'
    | '/admin/servicos'
    | '/api/booking'
    | '/api/cart-request'
    | '/api/contact'
    | '/api/health'
    | '/api/marketing-slides'
    | '/api/newsletter'
    | '/api/products'
    | '/api/professional-inquiry'
    | '/api/professional-spaces'
    | '/api/professionals'
    | '/api/services'
    | '/api/admin/appointments'
    | '/api/admin/dashboard'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/marketing-slides'
    | '/api/admin/products'
    | '/api/admin/professional-spaces'
    | '/api/admin/professionals'
    | '/api/admin/services'
    | '/api/booking/availability'
    | '/api/admin/appointments/$appointmentId'
    | '/api/admin/marketing-slides/$slideId'
    | '/api/admin/products/$productId'
    | '/api/admin/professional-spaces/$spaceId'
    | '/api/admin/professionals/$professionalId'
    | '/api/admin/services/$serviceId'
    | '/api/admin/appointments/$appointmentId/email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgendamentoRoute: typeof AgendamentoRoute
  ContactosRoute: typeof ContactosRoute
  FaqRoute: typeof FaqRoute
  GaleriaRoute: typeof GaleriaRoute
  LojaRoute: typeof LojaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  ApiBookingRoute: typeof ApiBookingRouteWithChildren
  ApiCartRequestRoute: typeof ApiCartRequestRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMarketingSlidesRoute: typeof ApiMarketingSlidesRoute
  ApiNewsletterRoute: typeof ApiNewsletterRoute
  ApiProductsRoute: typeof ApiProductsRoute
  ApiProfessionalInquiryRoute: typeof ApiProfessionalInquiryRoute
  ApiProfessionalSpacesRoute: typeof ApiProfessionalSpacesRoute
  ApiProfessionalsRoute: typeof ApiProfessionalsRoute
  ApiServicesRoute: typeof ApiServicesRoute
  ApiAdminAppointmentsRoute: typeof ApiAdminAppointmentsRouteWithChildren
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMarketingSlidesRoute: typeof ApiAdminMarketingSlidesRouteWithChildren
  ApiAdminProductsRoute: typeof ApiAdminProductsRouteWithChildren
  ApiAdminProfessionalSpacesRoute: typeof ApiAdminProfessionalSpacesRouteWithChildren
  ApiAdminProfessionalsRoute: typeof ApiAdminProfessionalsRouteWithChildren
  ApiAdminServicesRoute: typeof ApiAdminServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/services': {
      id: '/api/services'
      path: '/api/services'
      fullPath: '/api/services'
      preLoaderRoute: typeof ApiServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/professionals': {
      id: '/api/professionals'
      path: '/api/professionals'
      fullPath: '/api/professionals'
      preLoaderRoute: typeof ApiProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/professional-spaces': {
      id: '/api/professional-spaces'
      path: '/api/professional-spaces'
      fullPath: '/api/professional-spaces'
      preLoaderRoute: typeof ApiProfessionalSpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/professional-inquiry': {
      id: '/api/professional-inquiry'
      path: '/api/professional-inquiry'
      fullPath: '/api/professional-inquiry'
      preLoaderRoute: typeof ApiProfessionalInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter': {
      id: '/api/newsletter'
      path: '/api/newsletter'
      fullPath: '/api/newsletter'
      preLoaderRoute: typeof ApiNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketing-slides': {
      id: '/api/marketing-slides'
      path: '/api/marketing-slides'
      fullPath: '/api/marketing-slides'
      preLoaderRoute: typeof ApiMarketingSlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart-request': {
      id: '/api/cart-request'
      path: '/api/cart-request'
      fullPath: '/api/cart-request'
      preLoaderRoute: typeof ApiCartRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking': {
      id: '/api/booking'
      path: '/api/booking'
      fullPath: '/api/booking'
      preLoaderRoute: typeof ApiBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/servicos': {
      id: '/admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AdminServicosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profissionais': {
      id: '/admin/profissionais'
      path: '/profissionais'
      fullPath: '/admin/profissionais'
      preLoaderRoute: typeof AdminProfissionaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agendamentos': {
      id: '/admin/agendamentos'
      path: '/agendamentos'
      fullPath: '/admin/agendamentos'
      preLoaderRoute: typeof AdminAgendamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/booking/availability': {
      id: '/api/booking/availability'
      path: '/availability'
      fullPath: '/api/booking/availability'
      preLoaderRoute: typeof ApiBookingAvailabilityRouteImport
      parentRoute: typeof ApiBookingRoute
    }
    '/api/admin/services': {
      id: '/api/admin/services'
      path: '/api/admin/services'
      fullPath: '/api/admin/services'
      preLoaderRoute: typeof ApiAdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/professionals': {
      id: '/api/admin/professionals'
      path: '/api/admin/professionals'
      fullPath: '/api/admin/professionals'
      preLoaderRoute: typeof ApiAdminProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/professional-spaces': {
      id: '/api/admin/professional-spaces'
      path: '/api/admin/professional-spaces'
      fullPath: '/api/admin/professional-spaces'
      preLoaderRoute: typeof ApiAdminProfessionalSpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/products': {
      id: '/api/admin/products'
      path: '/api/admin/products'
      fullPath: '/api/admin/products'
      preLoaderRoute: typeof ApiAdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/marketing-slides': {
      id: '/api/admin/marketing-slides'
      path: '/api/admin/marketing-slides'
      fullPath: '/api/admin/marketing-slides'
      preLoaderRoute: typeof ApiAdminMarketingSlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/appointments': {
      id: '/api/admin/appointments'
      path: '/api/admin/appointments'
      fullPath: '/api/admin/appointments'
      preLoaderRoute: typeof ApiAdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/services/$serviceId': {
      id: '/api/admin/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/api/admin/services/$serviceId'
      preLoaderRoute: typeof ApiAdminServicesServiceIdRouteImport
      parentRoute: typeof ApiAdminServicesRoute
    }
    '/api/admin/professionals/$professionalId': {
      id: '/api/admin/professionals/$professionalId'
      path: '/$professionalId'
      fullPath: '/api/admin/professionals/$professionalId'
      preLoaderRoute: typeof ApiAdminProfessionalsProfessionalIdRouteImport
      parentRoute: typeof ApiAdminProfessionalsRoute
    }
    '/api/admin/professional-spaces/$spaceId': {
      id: '/api/admin/professional-spaces/$spaceId'
      path: '/$spaceId'
      fullPath: '/api/admin/professional-spaces/$spaceId'
      preLoaderRoute: typeof ApiAdminProfessionalSpacesSpaceIdRouteImport
      parentRoute: typeof ApiAdminProfessionalSpacesRoute
    }
    '/api/admin/products/$productId': {
      id: '/api/admin/products/$productId'
      path: '/$productId'
      fullPath: '/api/admin/products/$productId'
      preLoaderRoute: typeof ApiAdminProductsProductIdRouteImport
      parentRoute: typeof ApiAdminProductsRoute
    }
    '/api/admin/marketing-slides/$slideId': {
      id: '/api/admin/marketing-slides/$slideId'
      path: '/$slideId'
      fullPath: '/api/admin/marketing-slides/$slideId'
      preLoaderRoute: typeof ApiAdminMarketingSlidesSlideIdRouteImport
      parentRoute: typeof ApiAdminMarketingSlidesRoute
    }
    '/api/admin/appointments/$appointmentId': {
      id: '/api/admin/appointments/$appointmentId'
      path: '/$appointmentId'
      fullPath: '/api/admin/appointments/$appointmentId'
      preLoaderRoute: typeof ApiAdminAppointmentsAppointmentIdRouteImport
      parentRoute: typeof ApiAdminAppointmentsRoute
    }
    '/api/admin/appointments/$appointmentId/email': {
      id: '/api/admin/appointments/$appointmentId/email'
      path: '/email'
      fullPath: '/api/admin/appointments/$appointmentId/email'
      preLoaderRoute: typeof ApiAdminAppointmentsAppointmentIdEmailRouteImport
      parentRoute: typeof ApiAdminAppointmentsAppointmentIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendamentosRoute: typeof AdminAgendamentosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminProfissionaisRoute: typeof AdminProfissionaisRoute
  AdminServicosRoute: typeof AdminServicosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendamentosRoute: AdminAgendamentosRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminProfissionaisRoute: AdminProfissionaisRoute,
  AdminServicosRoute: AdminServicosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiBookingRouteChildren {
  ApiBookingAvailabilityRoute: typeof ApiBookingAvailabilityRoute
}

const ApiBookingRouteChildren: ApiBookingRouteChildren = {
  ApiBookingAvailabilityRoute: ApiBookingAvailabilityRoute,
}

const ApiBookingRouteWithChildren = ApiBookingRoute._addFileChildren(
  ApiBookingRouteChildren,
)

interface ApiAdminAppointmentsAppointmentIdRouteChildren {
  ApiAdminAppointmentsAppointmentIdEmailRoute: typeof ApiAdminAppointmentsAppointmentIdEmailRoute
}

const ApiAdminAppointmentsAppointmentIdRouteChildren: ApiAdminAppointmentsAppointmentIdRouteChildren =
  {
    ApiAdminAppointmentsAppointmentIdEmailRoute:
      ApiAdminAppointmentsAppointmentIdEmailRoute,
  }

const ApiAdminAppointmentsAppointmentIdRouteWithChildren =
  ApiAdminAppointmentsAppointmentIdRoute._addFileChildren(
    ApiAdminAppointmentsAppointmentIdRouteChildren,
  )

interface ApiAdminAppointmentsRouteChildren {
  ApiAdminAppointmentsAppointmentIdRoute: typeof ApiAdminAppointmentsAppointmentIdRouteWithChildren
}

const ApiAdminAppointmentsRouteChildren: ApiAdminAppointmentsRouteChildren = {
  ApiAdminAppointmentsAppointmentIdRoute:
    ApiAdminAppointmentsAppointmentIdRouteWithChildren,
}

const ApiAdminAppointmentsRouteWithChildren =
  ApiAdminAppointmentsRoute._addFileChildren(ApiAdminAppointmentsRouteChildren)

interface ApiAdminMarketingSlidesRouteChildren {
  ApiAdminMarketingSlidesSlideIdRoute: typeof ApiAdminMarketingSlidesSlideIdRoute
}

const ApiAdminMarketingSlidesRouteChildren: ApiAdminMarketingSlidesRouteChildren =
  {
    ApiAdminMarketingSlidesSlideIdRoute: ApiAdminMarketingSlidesSlideIdRoute,
  }

const ApiAdminMarketingSlidesRouteWithChildren =
  ApiAdminMarketingSlidesRoute._addFileChildren(
    ApiAdminMarketingSlidesRouteChildren,
  )

interface ApiAdminProductsRouteChildren {
  ApiAdminProductsProductIdRoute: typeof ApiAdminProductsProductIdRoute
}

const ApiAdminProductsRouteChildren: ApiAdminProductsRouteChildren = {
  ApiAdminProductsProductIdRoute: ApiAdminProductsProductIdRoute,
}

const ApiAdminProductsRouteWithChildren =
  ApiAdminProductsRoute._addFileChildren(ApiAdminProductsRouteChildren)

interface ApiAdminProfessionalSpacesRouteChildren {
  ApiAdminProfessionalSpacesSpaceIdRoute: typeof ApiAdminProfessionalSpacesSpaceIdRoute
}

const ApiAdminProfessionalSpacesRouteChildren: ApiAdminProfessionalSpacesRouteChildren =
  {
    ApiAdminProfessionalSpacesSpaceIdRoute:
      ApiAdminProfessionalSpacesSpaceIdRoute,
  }

const ApiAdminProfessionalSpacesRouteWithChildren =
  ApiAdminProfessionalSpacesRoute._addFileChildren(
    ApiAdminProfessionalSpacesRouteChildren,
  )

interface ApiAdminProfessionalsRouteChildren {
  ApiAdminProfessionalsProfessionalIdRoute: typeof ApiAdminProfessionalsProfessionalIdRoute
}

const ApiAdminProfessionalsRouteChildren: ApiAdminProfessionalsRouteChildren = {
  ApiAdminProfessionalsProfessionalIdRoute:
    ApiAdminProfessionalsProfessionalIdRoute,
}

const ApiAdminProfessionalsRouteWithChildren =
  ApiAdminProfessionalsRoute._addFileChildren(
    ApiAdminProfessionalsRouteChildren,
  )

interface ApiAdminServicesRouteChildren {
  ApiAdminServicesServiceIdRoute: typeof ApiAdminServicesServiceIdRoute
}

const ApiAdminServicesRouteChildren: ApiAdminServicesRouteChildren = {
  ApiAdminServicesServiceIdRoute: ApiAdminServicesServiceIdRoute,
}

const ApiAdminServicesRouteWithChildren =
  ApiAdminServicesRoute._addFileChildren(ApiAdminServicesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgendamentoRoute: AgendamentoRoute,
  ContactosRoute: ContactosRoute,
  FaqRoute: FaqRoute,
  GaleriaRoute: GaleriaRoute,
  LojaRoute: LojaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  ApiBookingRoute: ApiBookingRouteWithChildren,
  ApiCartRequestRoute: ApiCartRequestRoute,
  ApiContactRoute: ApiContactRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMarketingSlidesRoute: ApiMarketingSlidesRoute,
  ApiNewsletterRoute: ApiNewsletterRoute,
  ApiProductsRoute: ApiProductsRoute,
  ApiProfessionalInquiryRoute: ApiProfessionalInquiryRoute,
  ApiProfessionalSpacesRoute: ApiProfessionalSpacesRoute,
  ApiProfessionalsRoute: ApiProfessionalsRoute,
  ApiServicesRoute: ApiServicesRoute,
  ApiAdminAppointmentsRoute: ApiAdminAppointmentsRouteWithChildren,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMarketingSlidesRoute: ApiAdminMarketingSlidesRouteWithChildren,
  ApiAdminProductsRoute: ApiAdminProductsRouteWithChildren,
  ApiAdminProfessionalSpacesRoute: ApiAdminProfessionalSpacesRouteWithChildren,
  ApiAdminProfessionalsRoute: ApiAdminProfessionalsRouteWithChildren,
  ApiAdminServicesRoute: ApiAdminServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
